### ISSUE TITLE
提问后报错

### ISSUE THREAD

**Issue by rui12366B** [ddiu8081/chatgpt-demo#108]
### Describe the bug

提问后报错

### Reproduction

1

### System Info

```Shell
C:\Users\Administrator\Desktop\chatgpt-demo-main\C:\Users\Administrator\Desktop\chatgpt-demo-main\node_modules\undici\index.js:109:13
Open in editor
Stack Trace
TypeError: fetch failed
    at Proxy.fetch (C:\Users\Administrator\Desktop\chatgpt-demo-main\node_modules\undici\index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.post (C:\Users\Administrator\Desktop\chatgpt-demo-main\src\pages\api\generate.ts:19:20)
    at async call (file:///C:/Users/Administrator/Desktop/chatgpt-demo-main/node_modules/astro/dist/core/endpoint/index.js:71:20)
    at async call (file:///C:/Users/Administrator/Desktop/chatgpt-demo-main/node_modules/astro/dist/core/endpoint/dev/index.js:15:10)
    at async handleRoute (file:///C:/Users/Administrator/Desktop/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/route.js:117:20)
    at async run (file:///C:/Users/Administrator/Desktop/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/request.js:46:14)
    at async runWithErrorHandling (file:///C:/Users/Administrator/Desktop/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///C:/Users/Administrator/Desktop/chatgpt-demo-main/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:3)
Cause
{
  "errno": -4077,
  "code": "ECONNRESET",
  "syscall": "read"
}
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by farfarbiao** [comment]
我也遇到这样的问题了
