### ISSUE TITLE
npm run error

### ISSUE THREAD

**Issue by jaywongs** [ddiu8081/chatgpt-demo#30]
environment:
Linux instance-20211025-1400 5.15.0-1029-oracle #35~20.04.1-Ubuntu SMP Wed Jan 25 10:16:03 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
npm version v9.6.0
node version v16.19.1

error log :
```shell
root@instance:~/chatgpt/chatgpt-demo# npm run dev

> novel-gpt@0.0.1 dev
> astro dev

file:///root/chatgpt/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432
                            throw new TypeError(`${context} is not a ReadableStream.`);
                                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (file:///root/chatgpt/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432:21)
    at convertReadableWritablePair (file:///root/chatgpt/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3509:11)
    at ReadableStream.pipeThrough (file:///root/chatgpt/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3584:33)
    at fetchFinale (/root/chatgpt/chatgpt-demo/node_modules/undici/lib/fetch/index.js:973:52)
    at mainFetch (/root/chatgpt/chatgpt-demo/node_modules/undici/lib/fetch/index.js:773:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by rossroma** [comment]
the  same problem

**Comment by rossroma** [comment]
#2 update your node version

**Comment by kollyQAQ** [comment]
需要 node 18 以上版本
