### ISSUE TITLE
添加openai key部署后一直“fetch failed”

### ISSUE THREAD

**Issue by wangmingdong** [ddiu8081/chatgpt-demo#363]
### Describe the bug

添加openai key部署后一直“fetch failed”，服务部署期间一直需科学上网吗？

### Reproduction

TypeError: fetch failed

### System Info

```Shell
TypeError: fetch failed
    at Proxy.fetch (D:\work\chatgptDemo-main\node_modules\.pnpm\undici@5.21.0\node_modules\undici\index.js:109:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.post (D:\work\chatgptDemo-main\src\pages\api\generate.ts:40:20)
    at async call (file:///D:/work/chatgptDemo-main/node_modules/.pnpm/astro@2.1.3/node_modules/astro/dist/core/endpoint/index.js:71:20)
    at async call (file:///D:/work/chatgptDemo-main/node_modules/.pnpm/astro@2.1.3/node_modules/astro/dist/core/endpoint/dev/index.js:15:10)
    at async handleRoute (file:///D:/work/chatgptDemo-main/node_modules/.pnpm/astro@2.1.3/node_modules/astro/dist/vite-plugin-astro-server/route.js:117:20)
    at async run (file:///D:/work/chatgptDemo-main/node_modules/.pnpm/astro@2.1.3/node_modules/astro/dist/vite-plugin-astro-server/request.js:46:14)
    at async runWithErrorHandling (file:///D:/work/chatgptDemo-main/node_modules/.pnpm/astro@2.1.3/node_modules/astro/dist/vite-plugin-astro-server/controller.js:65:5)
    at async handleRequest (file:///D:/work/chatgptDemo-main/node_modules/.pnpm/astro@2.1.3/node_modules/astro/dist/vite-plugin-astro-server/request.js:40:3) {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (D:\work\chatgptDemo-main\node_modules\.pnpm\undici@5.21.0\node_modules\undici\lib\core\connect.js:182:24)
      at D:\work\chatgptDemo-main\node_modules\.pnpm\undici@5.21.0\node_modules\undici\lib\core\connect.js:129:46
      at Immediate._onImmediate (D:\work\chatgptDemo-main\node_modules\.pnpm\undici@5.21.0\node_modules\undici\lib\core\connect.js:168:33)
      at process.processImmediate (node:internal/timers:476:21) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ddiu8081/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/ddiu8081/.github/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by yzh990918** [comment]
This seems not be the deployment log.

**Comment by changzheng0101** [comment]
一样。。。我也遇见了这个问题

**Comment by ddiu8081** [comment]
The global proxy (and enhanced mode) needs to be enabled when running locally, or the HTTP proxy needs to be set for the interface using `HTTPS_PROXY`.
