### ISSUE TITLE
[GET] "http://esm.sh/@iconify-json/ph/icons.json": <no response> fetch failed

### ISSUE THREAD

**Issue by qintee** [ddiu8081/chatgpt-demo#462]
### What operating system are you using?

Windows && Ubuntu

### What browser are you using?

Chrome

### Describe the bug

I use a relay server to proxy the GPT connection and it work well perfectly but suddenly I can't use it anymore,no matter how many times I restart the service
I once speculated that the reason was an abnormality in the relay server,but after testing through other methods, OPENAI-API_KEY has no problem and can run on other services
I have also suspected that it is due to my local network. My cloud server has two gpt demo services, a few days ago one running well and the other failed. Now, all services have failed (including local services)

### Console Logs

Image show error messages in Linux and Text display the Windows local logs

`[GET] "http://esm.sh/@iconify-json/ph/icons.json": <no response> fetch failed
11:18:57 [vite] Error when evaluating SSR module astro:scripts/page-ssr.js: failed to import "/__uno.css"
|- FetchError: [GET] "http://esm.sh/@iconify-json/ph/icons.json": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:234:14)
    at async Object.$fetch2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:267:15)

11:18:57 [vite] Error when evaluating SSR module D:/Sofeware_collection/CODE/JaVaCode/GPT/chatgpt-demo-main/src/pages/index.astro: failed to import "astro:scripts/page-ssr.js"
|- FetchError: [GET] "http://esm.sh/@iconify-json/ph/icons.json": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:234:14)
    at async Object.$fetch2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:267:15)

 error   [GET] "http://esm.sh/@iconify-json/ph/icons.json": <no response> fetch failed
  File:
    D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:234:14
  Code:
    233 |       }
    > 234 |       return await onError(context);
          |              ^
      235 |     }
      236 |     const hasBody = context.response.body && !nullBodyResponses.has(context.response.status) && context.options.method !== "HEAD";
      237 |     if (hasBody) {
  Stacktrace:
FetchError: [GET] "http://esm.sh/@iconify-json/ph/icons.json": <no response> fetch failed
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:234:14)
    at async Object.$fetch2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:267:15)

  Cause:
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11457:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async $fetchRaw2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\of\shared\ofetch.92c14be7.cjs:225:26)
    at async $fetchRaw2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:234:14)
    at async Object.$fetch2 (D:\Sofeware_collection\CODE\JaVaCode\GPT\chatgpt-demo-main\node_modules\.pnpm\ofetch@1.3.3\node_modules\ofetch\dist\shared\ofetch.92c14be7.cjs:267:15)`

![bug1](https://github.com/anse-app/chatgpt-demo/assets/100121845/8a5ab31f-7827-42ea-a16a-6f9ad68e8a8b)
![bug2](https://github.com/anse-app/chatgpt-demo/assets/100121845/aba074fd-2c10-49b0-9859-baf4da533868)

### Participation

- [X] I am willing to submit a pull request for this issue.

**Comment by qintee** [comment]
I think I have identified the problem, I reopen my website on my phone and my PC can use service successfully.
So I think this issue is caused by accessing websites on mobile phones, which leads to service issues.
