### ISSUE TITLE
new TypeError(`${context} is not a ReadableStream.`)

### ISSUE THREAD

**Issue by westhuang** [ddiu8081/chatgpt-demo#93]
对npm这套不了解，执行run dev后出现下面报错，网上没查到相关资料，请帮忙看看～
信息如下：

westhuang@westhuangdeMacBook-Pro chatgpt-demo % npm run dev

> novel-gpt@0.0.1 dev
> astro dev

  🚀  astro  v2.0.17 started in 108ms

  ┃ Local    http://127.0.0.1:3000/
  ┃ Network  use --host to expose

file:///Users/westhuang/GitDir/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432
		            throw new TypeError(`${context} is not a ReadableStream.`);
		                  ^

TypeError: First parameter has member 'readable' that is not a ReadableStream.
    at assertReadableStream (file:///Users/westhuang/GitDir/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:432:21)
    at convertReadableWritablePair (file:///Users/westhuang/GitDir/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3509:11)
    at ReadableStream.pipeThrough (file:///Users/westhuang/GitDir/chatgpt-demo/node_modules/node-fetch-native/dist/shared/node-fetch-native.2b047dc1.mjs:3584:33)
    at fetchFinale (/Users/westhuang/GitDir/chatgpt-demo/node_modules/undici/lib/fetch/index.js:973:52)
    at mainFetch (/Users/westhuang/GitDir/chatgpt-demo/node_modules/undici/lib/fetch/index.js:773:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by MssText** [comment]
node版本 需要18+

**Comment by westhuang** [comment]
> node版本 需要18+

有用，3q～

**Comment by ddiu8081** [comment]
Duplicate of #65 .
